# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "15ae353b8f0f8255f3a643cb9515f77e"
name = "Seedform - Influencer Gifting"
application_url = "https://myseedform.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled", "app/scopes_update" ]
uri = "/webhooks/app-lifecycle"

[[webhooks.subscriptions]]
topics = [ "orders/create", "orders/cancelled", "fulfillments/create" ]
uri = "/webhooks/orders"

[[webhooks.subscriptions]]
topics = [ "draft_orders/delete" ]
uri = "/webhooks/draft-orders"

# MANDATORY PRIVACY WEBHOOKS
[[webhooks.subscriptions]]
compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_fulfillments,read_inventory,read_orders,write_orders,read_products,read_customers,write_customers,write_draft_orders,read_draft_orders"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://myseedform.vercel.app/auth"
]
