name: Contributor License Agreement (CLA)

on: []

jobs:
  cla:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - uses: Shopify/shopify-cla-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cla-token: ${{ secrets.CLA_TOKEN }}
